# Generated by Django 2.1 on 2018-08-07 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('town', '0002_game_playerstat_teamstat_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='town.Game'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(to='town.Game'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='town.Game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(to='town.Game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_games',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='town.Team'),
        ),
    ]
