# Generated by Django 2.1 on 2018-08-11 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0005_auto_20180809_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, to='town.Game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
