# Generated by Django 2.1 on 2018-08-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0009_auto_20180811_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='playerstat',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='teamstat',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userattribute',
            options={'ordering': ['-id']},
        ),
    ]
