# Generated by Django 2.1 on 2018-08-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0010_auto_20180811_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(blank=True, to='town.Tournament'),
        ),
    ]
