# Generated by Django 2.1 on 2018-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0011_team_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournaments',
            field=models.ManyToManyField(blank=True, to='town.Tournament'),
        ),
    ]
