# Generated by Django 2.1 on 2018-08-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0012_game_tournaments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['start_time']},
        ),
    ]
